<?php
/******************************************************************************
 *                                                                            *
 *    This file is part of RPB Chessboard, a Wordpress plugin.                *
 *    Copyright (C) 2013  Yoann Le Montagner <yo35 -at- melix.net>            *
 *                                                                            *
 *    This program is free software: you can redistribute it and/or modify    *
 *    it under the terms of the GNU General Public License as published by    *
 *    the Free Software Foundation, either version 3 of the License, or       *
 *    (at your option) any later version.                                     *
 *                                                                            *
 *    This program is distributed in the hope that it will be useful,         *
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
 *    GNU General Public License for more details.                            *
 *                                                                            *
 *    You should have received a copy of the GNU General Public License       *
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
 *                                                                            *
 ******************************************************************************/
?>

<div id="rpbchessboard-admin-help-pgn">

	<h3>
		<?php echo sprintf(
			__('Chess games with the %1$s[pgn][/pgn]%2$s tags', 'rpbchessboard'),
			'<span class="rpbchessboard-admin-code-inline">',
			'</span>'
		); ?>
	</h3>





	<h4><?php _e('PGN format', 'rpbchessboard'); ?></h4>

	<p>
		<?php echo sprintf(
			__(
				'The string between the %1$s[pgn][/pgn]%2$s tags describe the game. '.
				'The used notation follows the standard %3$sPGN format%4$s, and can '.
				'be automatically generated by the common chess database softwares, '.
				'including %5$sChessbase%6$s, %7$sScid%8$s, etc... '.
				'The PGN syntax is summarized here through a few representative examples.',
			'rpbchessboard'),
			'<span class="rpbchessboard-admin-code-inline">',
			'</span>',
			sprintf('<a href="%1$s" target="_blank">',
				__('http://en.wikipedia.org/wiki/Portable_Game_Notation', 'rpbchessboard')
			),
			'</a>',
			'<a href="http://www.chessbase.com/" target="_blank">',
			'</a>',
			'<a href="http://scid.sourceforge.net/" target="_blank">',
			'</a>'
		); ?>
	</p>





	<div id="rpbchessboard-admin-pgnExamples" class="rpbchessboard-admin-tabs">

		<ul>
			<li>Kasparov &ndash; Kramnik</li>
			<li><?php _e('Game with no headers'    , 'rpbchessboard'); ?></li>
			<li><?php _e('Custom starting position', 'rpbchessboard'); ?></li>
		</ul>


		<div>
			<div class="rpbchessboard-admin-columns">
				<div class="rpbchessboard-admin-column-left">
					<div class="rpbchessboard-admin-code-block">
						[pgn]<br/>
						<br/>
						[Event &quot;Linares 16&lt;sup&gt;th&lt;sup&gt;&quot;]<br/>
						[Site &quot;Linares&quot;]<br/>
						[Date &quot;1999.02.25&quot;]<br/>
						[Round &quot;4&quot;]<br/>
						[White &quot;Kasparov, Garry&quot;]<br/>
						[Black &quot;Kramnik, Vladimir&quot;]<br/>
						[Result &quot;1/2-1/2&quot;]<br/>
						[WhiteElo &quot;2812&quot;]<br/>
						[BlackElo &quot;2751&quot;]<br/>
						<br/>
						1. d4 Nf6 2. c4 e6 3. Nc3 Bb4 4. Qc2 d5 5. cxd5 Qxd5 6. Nf3 Qf5 7. Qxf5 exf5 8.
						a3 Be7 9. Bg5 Be6 10. e3 c6 11. Bd3 Nbd7 12. O-O h6 13. Bh4 a5 14. Rac1 O-O 15.
						Ne2 g5 16. Bg3 Ne4 17. Nc3 Nxc3 18. Rxc3 Nf6 19. Rcc1 Rfd8 20. Rfd1 Rac8 1/2-1/2<br/>
						<br/>
						[/pgn]
					</div>
				</div>
				<div class="rpbchessboard-admin-column-right">
					<div class="rpbchessboard-admin-visu-block">
						<div id="rpbchessboard-admin-examplePgn1-in" class="rpbchessboard-in">
							[Event &quot;Linares 16&lt;sup&gt;th&lt;sup&gt;&quot;]
							[Site &quot;Linares&quot;]
							[Date &quot;1999.02.25&quot;]
							[Round &quot;4&quot;]
							[White &quot;Kasparov, Garry&quot;]
							[Black &quot;Kramnik, Vladimir&quot;]
							[Result &quot;1/2-1/2&quot;]
							[WhiteElo &quot;2812&quot;]
							[BlackElo &quot;2751&quot;]
							1. d4 Nf6 2. c4 e6 3. Nc3 Bb4 4. Qc2 d5 5. cxd5 Qxd5 6. Nf3 Qf5 7. Qxf5 exf5 8.
							a3 Be7 9. Bg5 Be6 10. e3 c6 11. Bd3 Nbd7 12. O-O h6 13. Bh4 a5 14. Rac1 O-O 15.
							Ne2 g5 16. Bg3 Ne4 17. Nc3 Nxc3 18. Rxc3 Nf6 19. Rcc1 Rfd8 20. Rfd1 Rac8 1/2-1/2
						</div>
						<div id="rpbchessboard-admin-examplePgn1-out" class="rpbchessboard-out rpbchessboard-invisible">
							<?php include(RPBCHESSBOARD_ABSPATH.'templates/common/pgncontent.php'); ?>
						</div>
						<script type="text/javascript">
							processPGN('rpbchessboard-admin-examplePgn1-in', 'rpbchessboard-admin-examplePgn1-out');
						</script>
					</div>
				</div>
			</div>
		</div>


		<div>
			<div class="rpbchessboard-admin-columns">
				<div class="rpbchessboard-admin-column-left">
					<div class="rpbchessboard-admin-code-block">
						[pgn]<br/>
						1. e3 a5 2. Qh5 Ra6 3. Qxa5 h5 4. Qxc7 Rah6 5. h4 f6 6. Qxd7+ Kf7 7. Qxb7 Qd3
						8. Qxb8 Qh7 9. Qxc8 Kg6 10. Qe6 {<?php _e('Stalemate.', 'rpbchessboard'); ?>} *<br/>
						[/pgn]
					</div>
				</div>
				<div class="rpbchessboard-admin-column-right">
					<div class="rpbchessboard-admin-visu-block">
						<div id="rpbchessboard-admin-examplePgn2-in" class="rpbchessboard-in">
							1. e3 a5 2. Qh5 Ra6 3. Qxa5 h5 4. Qxc7 Rah6 5. h4 f6 6. Qxd7+ Kf7 7. Qxb7 Qd3
							8. Qxb8 Qh7 9. Qxc8 Kg6 10. Qe6 {<?php _e('Stalemate.', 'rpbchessboard'); ?>} *
						</div>
						<div id="rpbchessboard-admin-examplePgn2-out" class="rpbchessboard-out rpbchessboard-invisible">
							<?php include(RPBCHESSBOARD_ABSPATH.'templates/common/pgncontent.php'); ?>
						</div>
						<script type="text/javascript">
							processPGN('rpbchessboard-admin-examplePgn2-in', 'rpbchessboard-admin-examplePgn2-out');
						</script>
					</div>
				</div>
			</div>
			<p>
				<?php echo sprintf(
					__(
						'Normally, the strict PGN syntax requires that each PGN string starts with '.
						'7 compulsory headers: %1$s[Event &quot;...&quot;]%2$s, '.
						'%1$s[Site &quot;...&quot;]%2$s, %1$s[Date &quot;...&quot;]%2$s, '.
						'%1$s[Round &quot;...&quot;]%2$s, %1$s[White &quot;...&quot;]%2$s, '.
						'%1$s[Black &quot;...&quot;]%2$s, and %1$s[Result &quot;...&quot;]%2$s. '.
						'However, they are all optional here.',
					'rpbchessboard'),
					'<span class="rpbchessboard-admin-code-inline">',
					'</span>'
				); ?>
			</p>
		</div>


		<div>
			<div class="rpbchessboard-admin-columns">
				<div class="rpbchessboard-admin-column-left">
					<div class="rpbchessboard-admin-code-block">
						[pgn]<br/>
						<br/>
						[Event &quot;Wijk aan Zee&quot;]<br/>
						[Site &quot;Wijk aan Zee&quot;]<br/>
						[Date &quot;1999.01.20&quot;]<br/>
						[Round &quot;4&quot;]<br/>
						[White &quot;Kasparov, Garry&quot;]<br/>
						[Black &quot;Topalov, Veselin&quot;]<br/>
						[Result &quot;1-0&quot;]<br/>
						[WhiteElo &quot;2812&quot;]<br/>
						[BlackElo &quot;2700&quot;]<br/>
						[SetUp &quot;1&quot;]<br/>
						[FEN &quot;b2r3r/k4p1p/p2q1np1/NppP4/3p1Q2/P4PPB/1PP4P/1K1RR3 w - - 0 24&quot;]<br/>
						<br/>
						{[pgndiagram]}
						24. Rxd4 !! cxd4 25. Re7+ Kb6 26. Qxd4+ Kxa5 27. b4+ Ka4 28. Qc3 Qxd5 29. Ra7 Bb7
						30. Rxb7 Qc4 31. Qxf6 Kxa3 32. Qxa6+ Kxb4 33. c3+ Kxc3 34. Qa1+ Kd2 35. Qb2+
						Kd1 36. Bf1 Rd2 37. Rd7 Rxd7 38. Bxc4 bxc4 39. Qxh8 Rd3 40. Qa8 c3 41. Qa4+ Ke1
						42. f4 f5 43. Kc1 Rd2 44. Qa7 1-0<br/>
						<br/>
						[/pgn]
					</div>
					<p>
						<?php echo sprintf(
							__(
								'The %1$s[FEN &quot;...&quot;]%2$s header might be used to specify that the game '.
								'starts with a custom position. Additionally, the strict PGN syntax requires that '.
								'%1$s[SetUp &quot;1&quot;]%2$s is added when using the %1$s[FEN &quot;...&quot;]%2$s header.',
							'rpbchessboard'),
							'<span class="rpbchessboard-admin-code-inline">',
							'</span>'
						); ?>
					</p>
				</div>
				<div class="rpbchessboard-admin-column-right">
					<div class="rpbchessboard-admin-visu-block">
						<div id="rpbchessboard-admin-examplePgn3-in" class="rpbchessboard-in">
							[Event &quot;Wijk aan Zee&quot;]
							[Site &quot;Wijk aan Zee&quot;]
							[Date &quot;1999.01.20&quot;]
							[Round &quot;4&quot;]
							[White &quot;Kasparov, Garry&quot;]
							[Black &quot;Topalov, Veselin&quot;]
							[Result &quot;1-0&quot;]
							[WhiteElo &quot;2812&quot;]
							[BlackElo &quot;2700&quot;]
							[SetUp &quot;1&quot;]
							[FEN &quot;b2r3r/k4p1p/p2q1np1/NppP4/3p1Q2/P4PPB/1PP4P/1K1RR3 w - - 0 24&quot;]
							{&lt;span class=&quot;PgnWidget-anchor-diagram&quot;&gt;&lt;/span&gt;}
							24. Rxd4 !! cxd4 25. Re7+ Kb6 26. Qxd4+ Kxa5 27. b4+ Ka4 28. Qc3 Qxd5 29. Ra7 Bb7
							30. Rxb7 Qc4 31. Qxf6 Kxa3 32. Qxa6+ Kxb4 33. c3+ Kxc3 34. Qa1+ Kd2 35. Qb2+
							Kd1 36. Bf1 Rd2 37. Rd7 Rxd7 38. Bxc4 bxc4 39. Qxh8 Rd3 40. Qa8 c3 41. Qa4+ Ke1
							42. f4 f5 43. Kc1 Rd2 44. Qa7 1-0
						</div>
						<div id="rpbchessboard-admin-examplePgn3-out" class="rpbchessboard-out rpbchessboard-invisible">
							<?php include(RPBCHESSBOARD_ABSPATH.'templates/common/pgncontent.php'); ?>
						</div>
						<script type="text/javascript">
							processPGN('rpbchessboard-admin-examplePgn3-in', 'rpbchessboard-admin-examplePgn3-out',
								{squareSize: 28});
						</script>
					</div>
				</div>
			</div>
		</div>

	</div>





	<h4><?php _e('Annotations', 'rpbchessboard'); ?></h4>

	<div id="rpbchessboard-admin-pgnAnnotations" class="rpbchessboard-admin-columns">
		<div class="rpbchessboard-admin-column-left">
			<div class="rpbchessboard-admin-code-block">
				[pgn] 1.e4 !! ! !? ?! ? ?? +- +/- +/= = inf =/+ -/+ -+ * [/pgn]
			</div>
		</div>
		<div class="rpbchessboard-admin-column-right">
			<div class="rpbchessboard-admin-visu-block">
				<div id="rpbchessboard-admin-annotations-example-in" class="rpbchessboard-in">
					1.e4 !! ! !? ?! ? ?? +- +/- +/= = inf =/+ -/+ -+ *
				</div>
				<div id="rpbchessboard-admin-annotations-example-out" class="rpbchessboard-out rpbchessboard-invisible">
					<?php include(RPBCHESSBOARD_ABSPATH.'templates/common/pgncontent.php'); ?>
				</div>
				<script type="text/javascript">
					processPGN('rpbchessboard-admin-annotations-example-in', 'rpbchessboard-admin-annotations-example-out');
				</script>
			</div>
		</div>
	</div>

	<p>
		<?php echo sprintf(
			__(
				'Notice that the chess database softwares may introduce annotations such as '.
				'%1$s&quot;$x&quot;%2$s where %1$s&quot;x&quot;%2$s is replaced with one or more digits '.
				'(for instance, %1$s&quot;1.e4 $1&quot;%2$s). This is what is advocated by the PGN norm, '.
				'and there are equivalences between this syntax and the human-readable one '.
				'(for instance %1$s&quot;$1&quot;%2$s is equivalent to %1$s&quot;!&quot;%2$s). '.
				'Both syntaxes are understood by the RPB Chessboard plugin.',
			'rpbchessboard'),
			'<span class="rpbchessboard-admin-code-inline">',
			'</span>'
		); ?>
	</p>





	<h4><?php _e('Commentaries', 'rpbchessboard'); ?></h4>

	<div id="rpbchessboard-admin-pgnCommentaries" class="rpbchessboard-admin-columns">
		<div class="rpbchessboard-admin-column-left">
			<div class="rpbchessboard-admin-code-block">
				[pgn]<br/>
				1. d4
				{<?php
					echo sprintf(__('I\'m a %1$sshort%2$s commentary.', 'rpbchessboard'),
						'&lt;strong style=&quot;color:red;&quot;&gt;', '&lt;/strong&gt;');
				?>}
				1... Nf6 2. c4 e6 3. Nc3 Bb4 4. Qc2 d5 5. cxd5 Qxd5 6. Nf3 Qf5 7. Qxf5 exf5
				8. a3 Be7 9. Bg5 Be6 10. e3 c6 11. Bd3 Nbd7 12. O-O h6 13. Bh4<br/>
				<br/>
				{<?php
					echo sprintf(__('I\'m a %1$slong%2$s commentary.', 'rpbchessboard'),
						'&lt;strong style=&quot;color:red;&quot;&gt;', '&lt;/strong&gt;');
				?>}<br/>
				<br/>
				13... a5 14. Rac1 O-O 15. Ne2 g5 16. Bg3 Ne4 17. Nc3 Nxc3 18. Rxc3 Nf6
				19. Rcc1 Rfd8 20. Rfd1 Rac8 *<br/>
				[/pgn]
			</div>
		</div>
		<div class="rpbchessboard-admin-column-right">
			<div class="rpbchessboard-admin-visu-block">
				<div id="rpbchessboard-admin-commentaries-example-in" class="rpbchessboard-in">
					1. d4
					{<?php
						echo sprintf(__('I\'m a %1$sshort%2$s commentary.', 'rpbchessboard'),
							'&lt;strong style=&quot;color:red;&quot;&gt;', '&lt;/strong&gt;');
					?>}
					1... Nf6 2. c4 e6 3. Nc3 Bb4 4. Qc2 d5 5. cxd5 Qxd5 6. Nf3 Qf5 7. Qxf5 exf5
					8. a3 Be7 9. Bg5 Be6 10. e3 c6 11. Bd3 Nbd7 12. O-O h6 13. Bh4

					{<?php
						echo sprintf(__('I\'m a %1$slong%2$s commentary.', 'rpbchessboard'),
							'&lt;strong style=&quot;color:red;&quot;&gt;', '&lt;/strong&gt;');
					?>}

					13... a5 14. Rac1 O-O 15. Ne2 g5 16. Bg3 Ne4 17. Nc3 Nxc3 18. Rxc3 Nf6
					19. Rcc1 Rfd8 20. Rfd1 Rac8 *
				</div>
				<div id="rpbchessboard-admin-commentaries-example-out" class="rpbchessboard-out rpbchessboard-invisible">
					<?php include(RPBCHESSBOARD_ABSPATH.'templates/common/pgncontent.php'); ?>
				</div>
				<script type="text/javascript">
					processPGN('rpbchessboard-admin-commentaries-example-in', 'rpbchessboard-admin-commentaries-example-out');
				</script>
			</div>
		</div>
	</div>

	<p>
		<?php echo sprintf(
			__(
				'Text commentaries can be inserted, surrounded with braces. They can be rendered '.
				'either inlined within the move sequence (&quot;short commentary&quot; style), '.
				'or as separated blocks (&quot;long commentary&quot; style). To insert a commentary '.
				'as a separated block, let two blank lines before and after it in the PGN string. '.
				'Also, notice that HTML tags are allowed within commentaries.',
			'rpbchessboard'),
			'<span class="rpbchessboard-admin-code-inline">',
			'</span>'
		); ?>
	</p>





	<h4><?php _e('Variations', 'rpbchessboard'); ?></h4>

	<p>TODO</p>





	<h4>
		<?php echo sprintf(
			__('Diagrams with the %1$s[pgndiagram]%2$s tag', 'rpbchessboard'),
			'<span class="rpbchessboard-admin-code-inline">',
			'</span>'
		); ?>
	</h4>

	<div id="rpbchessboard-admin-pgnDiagrams" class="rpbchessboard-admin-columns">
		<div class="rpbchessboard-admin-column-left">
			<div class="rpbchessboard-admin-code-block">
				[pgn]<br/>
				1. e4 c5 {[pgndiagram]
				<?php
					_e('This opening is called the Sicilian defence. A possible continuation is:', 'rpbchessboard');
				?>}
				2. Nf3 d6 *<br/>
				[/pgn]
			</div>
			<p>
				<?php echo sprintf(
					__(
						'Notice that %1$s[pgndiagram]%2$s tags must be inserted only in PGN commentaries.',
					'rpbchessboard'),
					'<span class="rpbchessboard-admin-code-inline">',
					'</span>'
				); ?>
			</p>
		</div>
		<div class="rpbchessboard-admin-column-right">
			<div class="rpbchessboard-admin-visu-block">
				<div id="rpbchessboard-admin-pgnDiagrams-example-in" class="rpbchessboard-in">
					1. e4 c5 {&lt;span class=&quot;PgnWidget-anchor-diagram&quot;&gt;&lt;/span&gt;
					<?php
						_e('This opening is called the Sicilian defence. A possible continuation is:', 'rpbchessboard');
					?>}
					2. Nf3 d6 *
				</div>
				<div id="rpbchessboard-admin-pgnDiagrams-example-out" class="rpbchessboard-out rpbchessboard-invisible">
					<?php include(RPBCHESSBOARD_ABSPATH.'templates/common/pgncontent.php'); ?>
				</div>
				<script type="text/javascript">
					processPGN('rpbchessboard-admin-pgnDiagrams-example-in', 'rpbchessboard-admin-pgnDiagrams-example-out',
						{squareSize: 28});
				</script>
			</div>
		</div>
	</div>





	<h4><?php _e('Attributes', 'rpbchessboard'); ?></h4>

	<p>
		<?php echo sprintf(
			__(
				'The %1$s[pgn][/pgn]%2$s and %1$s[pgndiagram]%2$s tags accept the same attributes '.
				'as the %1$s[fen][/fen]%2$s ones. For instance, using '.
				'%1$s[pgn square_size=...] ... [/pgn]%2$s will affect the size of all the '.
				'chess diagrams inserted in the commentaries of the corresponding chess game. '.
				'Setting %1$s[pgndiagram square_size=...]%2$s will affect only the corresponding diagram.',
			'rpbchessboard'),
			'<span class="rpbchessboard-admin-code-inline">',
			'</span>'
		); ?>
	</p>

</div>
